baseURL = "https://zippy-cupcake-c876f6.netlify.app/"
languageCode = "de"
title = "Bewegungsmelder"
contentDir = "content"
[params]
  mainSections = ["posts"]
  [params.ananke]
    show_recent_posts = true
